-- MySQL Script generated by MySQL Workbench
-- Sun Oct 21 23:49:55 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zona_mysql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zona_mysql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zona_mysql` DEFAULT CHARACTER SET utf8 ;
USE `zona_mysql` ;

-- -----------------------------------------------------
-- Table `zona_mysql`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zona_mysql`.`administrador` ;

CREATE TABLE IF NOT EXISTS `zona_mysql`.`administrador` (
  `idadministrador` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `anombre` VARCHAR(65) NOT NULL,
  `cedula` INT NOT NULL,
  `telefono` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zona_mysql`.`zonaresidencial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zona_mysql`.`zonaresidencial` ;

CREATE TABLE IF NOT EXISTS `zona_mysql`.`zonaresidencial` (
  `idzonaresidencial` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idzonaresidencial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zona_mysql`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zona_mysql`.`persona` ;

CREATE TABLE IF NOT EXISTS `zona_mysql`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `pnombre` VARCHAR(65) NULL,
  `pcedula` VARCHAR(45) NULL,
  `ptelefono` VARCHAR(45) NULL,
  `prol` VARCHAR(45) NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zona_mysql`.`fecha_visita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zona_mysql`.`fecha_visita` ;

CREATE TABLE IF NOT EXISTS `zona_mysql`.`fecha_visita` (
  `idfecha_visita` INT NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_final` VARCHAR(45) NULL,
  `persona_idpersona` INT NULL,
  UNIQUE INDEX `cuota_UNIQUE` (`idfecha_visita` ASC),
  INDEX `fk_fecha_visita_persona1_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_fecha_visita_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `zona_mysql`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zona_mysql`.`parqueadero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zona_mysql`.`parqueadero` ;

CREATE TABLE IF NOT EXISTS `zona_mysql`.`parqueadero` (
  `idparqueadero` INT NOT NULL AUTO_INCREMENT,
  `referencia` VARCHAR(45) NULL,
  PRIMARY KEY (`idparqueadero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zona_mysql`.`vivienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zona_mysql`.`vivienda` ;

CREATE TABLE IF NOT EXISTS `zona_mysql`.`vivienda` (
  `idvivienda` INT NOT NULL AUTO_INCREMENT,
  `vrol` VARCHAR(45) NULL,
  `vnombre` VARCHAR(45) NULL,
  `vpiso` INT NULL,
  `vbloque` VARCHAR(45) NULL,
  `persona_idpersona` INT NULL,
  `parqueadero_idparqueadero` INT NULL,
  `zonaresidencial_idzonaresidencial` INT NULL,
  PRIMARY KEY (`idvivienda`),
  INDEX `fk_vivienda_persona1_idx` (`persona_idpersona` ASC),
  INDEX `fk_vivienda_parqueadero1_idx` (`parqueadero_idparqueadero` ASC),
  INDEX `fk_vivienda_zonaresidencial1_idx` (`zonaresidencial_idzonaresidencial` ASC),
  CONSTRAINT `fk_vivienda_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `zona_mysql`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vivienda_parqueadero1`
    FOREIGN KEY (`parqueadero_idparqueadero`)
    REFERENCES `zona_mysql`.`parqueadero` (`idparqueadero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vivienda_zonaresidencial1`
    FOREIGN KEY (`zonaresidencial_idzonaresidencial`)
    REFERENCES `zona_mysql`.`zonaresidencial` (`idzonaresidencial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zona_mysql`.`cuota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zona_mysql`.`cuota` ;

CREATE TABLE IF NOT EXISTS `zona_mysql`.`cuota` (
  `idcuota` INT NOT NULL,
  `porcentage` DOUBLE NULL,
  `precio` VARCHAR(45) NULL,
  `persona_idpersona` INT NULL,
  PRIMARY KEY (`idcuota`),
  INDEX `fk_cuota_persona_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_cuota_persona`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `zona_mysql`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
