-- MySQL Script generated by MySQL Workbench
-- Sun Oct  7 20:22:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zona_mysql
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zona_mysql` ;

-- -----------------------------------------------------
-- Schema zona_mysql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zona_mysql` DEFAULT CHARACTER SET utf8 ;
USE `zona_mysql` ;

-- -----------------------------------------------------
-- Table `zona_mysql`.`spadministrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zona_mysql`.`spadministrador` (
  `spcedula` INT NOT NULL,
  `spnombre` VARCHAR(60) NOT NULL,
  `sptelefono` VARCHAR(45) NULL,
  `spusuario` VARCHAR(65) NOT NULL,
  `sppass` VARCHAR(64) NOT NULL,
  `spdireccion` VARCHAR(80) NULL,
  PRIMARY KEY (`spcedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zona_mysql`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zona_mysql`.`administrador` (
  `adcedula` VARCHAR(65) NOT NULL,
  `adnombre` VARCHAR(65) NOT NULL,
  `adtelefono` INT NULL,
  `addireccion` VARCHAR(85) NULL,
  `aduser` VARCHAR(65) NOT NULL,
  `adpass` VARCHAR(65) NOT NULL,
  `spadministrador_spcedula` INT NOT NULL,
  `spadministrador_spcedula1` INT NOT NULL,
  PRIMARY KEY (`adcedula`, `spadministrador_spcedula`),
  INDEX `fk_administrador_spadministrador_idx` (`spadministrador_spcedula1` ASC),
  CONSTRAINT `fk_administrador_spadministrador`
    FOREIGN KEY (`spadministrador_spcedula1`)
    REFERENCES `zona_mysql`.`spadministrador` (`spcedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zona_mysql`.`zonaResidencial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zona_mysql`.`zonaResidencial` (
  `idzonaResidencial` INT NOT NULL AUTO_INCREMENT,
  `zestrato` INT NOT NULL,
  `zdireccion` VARCHAR(65) NULL,
  `znombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idzonaResidencial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zona_mysql`.`parqueadero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zona_mysql`.`parqueadero` (
  `idparqueadero` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idparqueadero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zona_mysql`.`cuota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zona_mysql`.`cuota` (
  `idcuota` INT NOT NULL AUTO_INCREMENT,
  `ccuota` DECIMAL NULL,
  `cporcentaje` DECIMAL NOT NULL,
  PRIMARY KEY (`idcuota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zona_mysql`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zona_mysql`.`persona` (
  `idcedula` VARCHAR(65) NOT NULL,
  `pnombre` VARCHAR(65) NOT NULL,
  `ptelefono` VARCHAR(45) NULL,
  `pdireccion` VARCHAR(65) NULL,
  `prol` VARCHAR(65) NOT NULL,
  `cuota_idcuota` INT NOT NULL,
  PRIMARY KEY (`idcedula`),
  INDEX `fk_persona_cuota1_idx` (`cuota_idcuota` ASC),
  CONSTRAINT `fk_persona_cuota1`
    FOREIGN KEY (`cuota_idcuota`)
    REFERENCES `zona_mysql`.`cuota` (`idcuota`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zona_mysql`.`vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zona_mysql`.`vivienda` (
  `vpid` VARCHAR(65) NOT NULL,
  `vbloque` VARCHAR(65) NULL,
  `vpiso` INT NULL,
  `idzonaResidencial` INT NOT NULL,
  `vrol` VARCHAR(45) NOT NULL,
  `parqueadero_idparqueadero` VARCHAR(30) NOT NULL,
  `persona_idcedula` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`vpid`),
  INDEX `fk_apartamento_zonaResidencial1_idx` (`idzonaResidencial` ASC),
  INDEX `fk_vivienda_parqueadero1_idx` (`parqueadero_idparqueadero` ASC),
  INDEX `fk_vivienda_persona1_idx` (`persona_idcedula` ASC),
  CONSTRAINT `fk_apartamento_zonaResidencial1`
    FOREIGN KEY (`idzonaResidencial`)
    REFERENCES `zona_mysql`.`zonaResidencial` (`idzonaResidencial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vivienda_parqueadero1`
    FOREIGN KEY (`parqueadero_idparqueadero`)
    REFERENCES `zona_mysql`.`parqueadero` (`idparqueadero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vivienda_persona1`
    FOREIGN KEY (`persona_idcedula`)
    REFERENCES `zona_mysql`.`persona` (`idcedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zona_mysql`.`gestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zona_mysql`.`gestion` (
  `administrador_adcedula` VARCHAR(65) NOT NULL,
  `administrador_spadministrador_spcedula` INT NOT NULL,
  `zonaResidencial_idzonaResidencial` INT NOT NULL,
  INDEX `fk_gestion_administrador1_idx` (`administrador_adcedula` ASC, `administrador_spadministrador_spcedula` ASC),
  INDEX `fk_gestion_zonaResidencial1_idx` (`zonaResidencial_idzonaResidencial` ASC),
  CONSTRAINT `fk_gestion_administrador1`
    FOREIGN KEY (`administrador_adcedula` , `administrador_spadministrador_spcedula`)
    REFERENCES `zona_mysql`.`administrador` (`adcedula` , `spadministrador_spcedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gestion_zonaResidencial1`
    FOREIGN KEY (`zonaResidencial_idzonaResidencial`)
    REFERENCES `zona_mysql`.`zonaResidencial` (`idzonaResidencial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zona_mysql`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `zona_mysql`.`horario` (
  `fecha_entrada` VARCHAR(20) NOT NULL,
  `fecha_salida` VARCHAR(45) NULL,
  `persona_idcedula` VARCHAR(65) NOT NULL,
  INDEX `fk_horario_persona1_idx` (`persona_idcedula` ASC),
  UNIQUE INDEX `fecha_entrada_UNIQUE` (`fecha_entrada` ASC),
  CONSTRAINT `fk_horario_persona1`
    FOREIGN KEY (`persona_idcedula`)
    REFERENCES `zona_mysql`.`persona` (`idcedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
